version: "3.8"

services:
  
  identity:
    image: identity-image
    container_name: identity
    build:
      context: .
      dockerfile: Identity/Dockerfile
    depends_on:
      - api
    ports:
      - "10001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
  
  web:
    image: web-image
    container_name: web
    build:
      context: .
      dockerfile: Web/Dockerfile
    depends_on:
      - identity
    ports:
      - "10002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      
  api: 
    image: api-image
    container_name: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      - api-db  
      - cache
      - rabbitmq
    ports:
      - "10000:80"  
    environment:
      ASPNETCORE_ENVIRONMENT: Production
  
  api-db: 
    container_name: api-db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: strong
      
  cache:
    container_name: cache
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
      
        
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"      