version: "3.8"

services:
  api: 
    image: api-image
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      - api-db  
    ports:
      - "10000:80"  
    environment:
      ASPNETCORE_ENVIRONMENT: Production
  
  api-db: 
    container_name: api-db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: strong
      
  cache:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
      
    
        