version: "3.8"

services:
  app: 
    image: app-image
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db  
    ports:
      - "10000:80"  
    environment:
      ASPNETCORE_ENVIRONMENT: Production
  
  db: 
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: strong