version: "3.8"

services:
  app: 
    image: app-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:80"  
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  
  