version: "3.8"

services:
  local-db:
    image: postgres:latest
    ports:
      - "35432:5432"
    environment:
      POSTGRES_PASSWORD: strong
  cache:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"  