// <auto-generated />
using System;
using CodingLibraryDSR.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodingLibraryDSR.Data.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodingLibraryDSR.Data.Entity.Categories", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<string>("DifficultyIndex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficulty_index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Uid")
                        .HasName("pk_categories");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_uid");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("CodingLibraryDSR.Data.Entity.Comments", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<string>("ContentComments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_comments");

                    b.Property<DateTime>("LeftTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_time");

                    b.Property<Guid?>("ProblemsUid")
                        .HasColumnType("uuid")
                        .HasColumnName("problems_uid");

                    b.Property<Guid?>("UsersUid")
                        .HasColumnType("uuid")
                        .HasColumnName("users_uid");

                    b.HasKey("Uid")
                        .HasName("pk_comments");

                    b.HasIndex("ProblemsUid")
                        .HasDatabaseName("ix_comments_problems_uid");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("ix_comments_uid");

                    b.HasIndex("UsersUid")
                        .HasDatabaseName("ix_comments_users_uid");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("CodingLibraryDSR.Data.Entity.Languages", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Uid")
                        .HasName("pk_languages");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("ix_languages_uid");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("CodingLibraryDSR.Data.Entity.Problems", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<Guid?>("CategoriesUid")
                        .HasColumnType("uuid")
                        .HasColumnName("categories_uid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DifficultIndex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficult_index");

                    b.Property<Guid?>("LanguagesUid")
                        .HasColumnType("uuid")
                        .HasColumnName("languages_uid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solution");

                    b.HasKey("Uid")
                        .HasName("pk_problems");

                    b.HasIndex("CategoriesUid")
                        .HasDatabaseName("ix_problems_categories_uid");

                    b.HasIndex("LanguagesUid")
                        .HasDatabaseName("ix_problems_languages_uid");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("ix_problems_uid");

                    b.ToTable("problems", (string)null);
                });

            modelBuilder.Entity("CodingLibraryDSR.Data.Entity.Subscriptions", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<Guid?>("ProblemsUid")
                        .HasColumnType("uuid")
                        .HasColumnName("problems_uid");

                    b.Property<string>("StatusSubscriptions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_subscriptions");

                    b.Property<Guid?>("UsersUid")
                        .HasColumnType("uuid")
                        .HasColumnName("users_uid");

                    b.HasKey("Uid")
                        .HasName("pk_subscriptions");

                    b.HasIndex("ProblemsUid")
                        .HasDatabaseName("ix_subscriptions_problems_uid");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_uid");

                    b.HasIndex("UsersUid")
                        .HasDatabaseName("ix_subscriptions_users_uid");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("CodingLibraryDSR.Data.Entity.Users", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_status");

                    b.HasKey("Uid")
                        .HasName("pk_users");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("ix_users_uid");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CodingLibraryDSR.Data.Entity.Comments", b =>
                {
                    b.HasOne("CodingLibraryDSR.Data.Entity.Problems", null)
                        .WithMany("Comments")
                        .HasForeignKey("ProblemsUid")
                        .HasConstraintName("fk_comments_problems_problems_temp_id");

                    b.HasOne("CodingLibraryDSR.Data.Entity.Users", null)
                        .WithMany("Comments")
                        .HasForeignKey("UsersUid")
                        .HasConstraintName("fk_comments_users_users_uid");
                });

            modelBuilder.Entity("CodingLibraryDSR.Data.Entity.Problems", b =>
                {
                    b.HasOne("CodingLibraryDSR.Data.Entity.Categories", null)
                        .WithMany("Problems")
                        .HasForeignKey("CategoriesUid")
                        .HasConstraintName("fk_problems_categories_categories_uid");

                    b.HasOne("CodingLibraryDSR.Data.Entity.Languages", null)
                        .WithMany("Problems")
                        .HasForeignKey("LanguagesUid")
                        .HasConstraintName("fk_problems_languages_languages_uid");
                });

            modelBuilder.Entity("CodingLibraryDSR.Data.Entity.Subscriptions", b =>
                {
                    b.HasOne("CodingLibraryDSR.Data.Entity.Problems", null)
                        .WithMany("Subscritions")
                        .HasForeignKey("ProblemsUid")
                        .HasConstraintName("fk_subscriptions_problems_problems_uid");

                    b.HasOne("CodingLibraryDSR.Data.Entity.Users", null)
                        .WithMany("Subscritions")
                        .HasForeignKey("UsersUid")
                        .HasConstraintName("fk_subscriptions_users_users_uid");
                });

            modelBuilder.Entity("CodingLibraryDSR.Data.Entity.Categories", b =>
                {
                    b.Navigation("Problems");
                });

            modelBuilder.Entity("CodingLibraryDSR.Data.Entity.Languages", b =>
                {
                    b.Navigation("Problems");
                });

            modelBuilder.Entity("CodingLibraryDSR.Data.Entity.Problems", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Subscritions");
                });

            modelBuilder.Entity("CodingLibraryDSR.Data.Entity.Users", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Subscritions");
                });
#pragma warning restore 612, 618
        }
    }
}
